# Generated by Django 5.2.2 on 2025-07-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(null=True)),
                ('nom', models.TextField(null=True)),
                ('nom_latin', models.TextField(null=True)),
                ('famille', models.TextField(null=True)),
                ('origine', models.TextField(null=True)),
                ('milieu_naturel', models.TextField(null=True)),
                ('type_sol', models.TextField(null=True)),
                ('besoin_en_eau', models.TextField(null=True)),
                ('exposition', models.TextField(null=True)),
                ('temperature_air_min', models.TextField(null=True)),
                ('temperature_air_max', models.TextField(null=True)),
                ('humidite_air_min', models.TextField(null=True)),
                ('humidite_air_max', models.TextField(null=True)),
                ('humidite_sol_min', models.TextField(null=True)),
                ('humidite_sol_max', models.TextField(null=True)),
                ('luminosite_min', models.TextField(null=True)),
                ('luminosite_max', models.TextField(null=True)),
                ('ph_min', models.TextField(null=True)),
                ('ph_max', models.TextField(null=True)),
                ('periode_plantation', models.TextField(null=True)),
                ('periode_recolte', models.TextField(null=True)),
                ('temps_de_pousse', models.TextField(null=True)),
                ('engrais_recommande', models.TextField(null=True)),
                ('sensibilite', models.TextField(null=True)),
                ('difficulty', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('compatibility', models.TextField(null=True)),
                ('compatibilityReasons', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userDonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSaved', models.TextField(max_length=6000, null=True)),
                ('fullName', models.TextField(max_length=6000, null=True)),
                ('mail', models.TextField(max_length=6000, null=True)),
                ('mdp', models.TextField(max_length=6000, null=True)),
                ('informations', models.TextField(max_length=6000, null=True)),
            ],
        ),
    ]
