# Generated by Django 5.2.2 on 2025-07-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgriSmart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantinfo',
            old_name='compatibility',
            new_name='difficulte',
        ),
        migrations.RemoveField(
            model_name='plantinfo',
            name='compatibilityReasons',
        ),
        migrations.RemoveField(
            model_name='plantinfo',
            name='difficulty',
        ),
    ]
