# Generated by Django 5.2.2 on 2025-08-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriSmart', '0002_rename_compatibility_plantinfo_difficulte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprio', models.CharField(max_length=255)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type_alerte', models.CharField(choices=[('critical', 'Critique'), ('warning', 'Avertissement'), ('info', 'Information')], default='info', max_length=10)),
                ('urgence', models.IntegerField(choices=[(1, 'Très faible'), (2, 'Faible'), (3, 'Moyen'), (4, 'Élevé'), (5, 'Critique')], default=1)),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_resolue', models.BooleanField(default=False)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-urgence', '-date_creation'],
            },
        ),
    ]
