# Generated by Django 5.2.3 on 2025-09-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgriSmart', '0003_alertemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDataHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('soil_humidity', 'Humidité du sol'), ('temperature', 'Température'), ('air_humidity', "Humidité de l'air"), ('soil_ph', 'pH du sol'), ('nitrogen', 'Azote (N)'), ('phosphorus', 'Phosphore (P)'), ('potassium', 'Potassium (K)')], max_length=20)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor_type', '-timestamp'], name='AgriSmart_s_sensor__cd5ea8_idx')],
            },
        ),
    ]
